name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README
        env:
          STATS_TOKEN: ${{ secrets.STATS_TOKEN }}
        run: |
          sed -i "s/&token=.*/&token=${STATS_TOKEN}/g" README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with token" || echo "No changes to commit"
          git push
